Q1:

In [1]:
from array import *
array_num = array('i', [1, 3, 5, 3, 7, 1, 9, 3])
print("Original array: "+str(array_num))
num_list = array_num.tolist()
print("Convert the said array to an ordinary list with the same items:")
print(num_list)

Original array: array('i', [1, 3, 5, 3, 7, 1, 9, 3])
Convert the said array to an ordinary list with the same items:
[1, 3, 5, 3, 7, 1, 9, 3]


Q2:

In [3]:
import numpy as np
m = np.arange(6).reshape(2,3)
print("Original matrix:")
print(m)
result =  np.trace(m)
print("Condition number of the said matrix:")
print(result)

Original matrix:
[[0 1 2]
 [3 4 5]]
Condition number of the said matrix:
4


Q5:

In [4]:
import numpy as np
print("Original matrix:\n")
X = np.random.rand(5, 10)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.72218252 0.51588539 0.10101656 0.52808267 0.31516222 0.60243611
  0.09542952 0.11847125 0.80872221 0.86475589]
 [0.29553366 0.01052575 0.4803015  0.64173865 0.29694528 0.85565064
  0.57346381 0.15282386 0.47021204 0.0241595 ]
 [0.57944588 0.59424815 0.81587289 0.37502944 0.86667573 0.41661836
  0.7952816  0.28761107 0.20650634 0.67662068]
 [0.29523394 0.55705173 0.92390551 0.38671576 0.16406004 0.87098748
  0.74003039 0.36898928 0.04940498 0.84058693]
 [0.95439026 0.87814223 0.29656207 0.62898761 0.32490204 0.73427581
  0.2569515  0.67529878 0.50984338 0.48074194]]

Subtract the mean of each row of the said matrix:

[[ 0.25496809  0.04867096 -0.36619788  0.06086823 -0.15205221  0.13522168
  -0.37178491 -0.34874318  0.34150778  0.39754145]
 [-0.0846018  -0.36960972  0.10016603  0.26160318 -0.08319019  0.47551517
   0.19332834 -0.22731161  0.09007657 -0.35597597]
 [ 0.01805486  0.03285713  0.25448188 -0.18636158  0.30528471 -0.14477265
   0.23389059 -0.27377994 -0.3

Q3:

In [6]:
import numpy as np
arr = np.array([41,42,43,44])
x = [True,False,True,False]
newarr = arr[x]
print(newarr)

[41 43]


Q4:

In [7]:
import numpy as np
A = np.array([1,3,4,8,9])
B = np.array ([4,6,7,5,2])
C = A+B
print (C)

[ 5  9 11 13 11]
